export enum TableTargetsEnum {
  root = 'root',
  table = 'table',
  tableHead = 'tableHead',
  tableHeadRow = 'tableHeadRow',
  tableHeadCell = 'tableHeadCell',
  tableBody = 'tableBody',
  tableBodyRow = 'tableBodyRow',
  tableBodyCell = 'tableBodyCell',
  groupedCell = 'groupedCell',
  tablePaper = 'tablePaper',
  tableContainer = 'tableContainer',
  tablePaginationToolbar = 'tablePaginationToolbar',
  tablePaginationToolbarSelect = 'tablePaginationToolbarSelect',
  tablePaginationToolbarSelectMenu = 'tablePaginationToolbarSelectMenu',
}
