export enum ColumnFilterOptions {
  Between = 'between',
  BetweenInclusive = 'betweenInclusive',
  Contains = 'contains',
  Empty = 'empty',
  EndsWith = 'endsWith',
  Equals = 'equals',
  Fuzzy = 'fuzzy',
  GreaterThan = 'greaterThan',
  GreaterThanOrEqualTo = 'greaterThanOrEqualTo',
  LessThan = 'lessThan',
  LessThanOrEqualTo = 'lessThanOrEqualTo',
  NotEmpty = 'notEmpty',
  NotEquals = 'notEquals',
  StartsWith = 'startsWith',
  IncludesString = 'includesString',
  IncludesStringSensitive = 'includesStringSensitive',
  EqualsString = 'equalsString',
  ArrIncludes = 'arrIncludes',
  ArrIncludesAll = 'arrIncludesAll',
  ArrIncludesSome = 'arrIncludesSome',
  WeakEquals = 'weakEquals',
  InNumberRange = 'inNumberRange',
}
