export enum OpsBuilderTargets {
  root = 'root',
  editor = 'editor',
  actions = 'actions',
  close = 'close',
  events = 'events',
  eventSelector = 'eventSelector',
  eventOptions = 'eventOptions',
  eventOption = 'eventOption',
  deleteEvent = 'deleteEvent',
  operations = 'operations',
  operationSelector = 'operationSelector',
  operationOptions = 'operationOptions',
  operationOption = 'operationOption',
  operationDetails = 'operationDetails',
  operationForm = 'operationForm',
  operationActions = 'operationActions',
  saveOperation = 'saveOperation',
  cancelOperation = 'cancelOperation',
  operationList = 'operationList',
  operationItem = 'operationItem',
  operationType = 'operationType',
  editOperation = 'editOperation',
  deleteOperation = 'deleteOperation',
  moveUpOperation = 'moveUpOperation',
  moveDownOperation = 'moveDownOperation',
}
