export enum CanvasTargetsEnum {
  root = 'root',
  canvas = 'canvas',
  canvasEmpty = 'canvasEmpty',
  dropzone = 'dropzone',
  dropzoneWrapper = 'dropzoneWrapper',
  representationViewWrapper = 'representationViewWrapper',
  dragPreview = 'dragPreview',
  canvasItemHeader = 'canvasItemHeader',
  canvasItemHeaderWrapper = 'canvasItemHeaderWrapper',
  representationWrapper = 'representationWrapper',
  representationButtonsOpenEllipse = 'representationButtonsOpenEllipse',
  canvasButtonsWrapper = 'canvasButtonsWrapper',
  representationButtonsWrapper = 'representationButtonsWrapper',
  representationInformationWrapper = 'representationInformationWrapper',
  representationInformationSectionWrapper = 'representationInformationSectionWrapper',
}
