export enum CommonTargets {
  errorsFieldError = 'errorsFieldError',
  errorsRoot = 'errorsRoot',
  errorsUnorderedList = 'errorsUnorderedList',
  errorsUnorderedListItem = 'errorsUnorderedListItem',
  helperText = 'helperText',
  inputPrefix = 'inputPrefix',
  inputSuffix = 'inputSuffix',
  label = 'label',
  readOnly = 'readOnly',
  root = 'root',
  subLabel = 'subLabel',
  tooltipButton = 'tooltipButton',
  tooltipPopover = 'tooltipPopover',
}
