/**
 * Team:
 *
 * As we discussed at the huddle, these strings are 100% up for design.
 *
 * We need to create a structure that allows us to support wildcard events
 * which gives us insane observability and powerful Runtime API for our
 * future analytics and debugging features.
 */
export enum EventType {
  ANGULAR = 'angular',
  API_CALL_SENT = 'system.operation.api_call.sent',
  CONTAINER_DESTROY = 'system.containers.destroy',
  EFFECT_COMPLETED = 'system.effects.completed',
  EFFECT_FAILED = 'system.effects.failed',
  EFFECT_REGISTERED = 'system.effects.registered',
  EFFECT_TRIGGERED = 'system.effects.triggered',
  EFFECT_FULFILLED = 'system.effects.fulfilled',
  ENTITY_DESTROYED = 'system.entity.destroyed',
  ENTITY_REGISTERED = 'system.entity.registered',
  EVENT_EMIT = 'system.meta.event.emit',
  EVENT_EMITTED = 'system.meta.event.emitted',
  MODULE_COMPONENTS_DESTROYED = 'system.module.components.destroyed',
  MODULE_COMPONENTS_INIT = 'system.module.components.init',
  MODULE_COMPONENTS_READY = 'system.module.components.ready',
  MODULE_COMPONENTS_STARTED = 'system.module.components.started',
  MODULE_STORED = 'system.module.stored',
  MODULE_DESTROYED = 'system.module.destroyed',
  MODULE_INIT = 'system.module.init',
  MODULE_INITIALIZED = 'system.module.initialized',
  MODULE_INSERTED = 'system.slot.module.inserted',
  MODULE_LOADED = 'system.module.loaded',
  MODULE_READY = 'system.module.ready',
  MODULE_REQUESTED = 'system.module.requested',
  MODULE_STARTED = 'system.module.started',
  OBJECT_INITIALIZED = 'system.object.initialized',
  OBJECT_VALIDATED = 'system.validation.validated',
  ON_BLUR = 'onBlur',
  ON_CHANGE = 'onChange',
  ON_CLEAR = 'onClear',
  ON_CLICK = 'onClick',
  ON_CLOSE = 'onClose',
  ON_DROP = 'onDrop',
  ON_EDIT_SUBMISSION = 'onEditSubmission',
  ON_EXECUTE = 'onExecute',
  ON_FINISH_COUNTING = 'onFinishCounting',
  ON_FOCUS = 'onFocus',
  ON_INITIALIZE = 'onInitialize',
  ON_KEYSTROKE = 'onKeystroke',
  ON_MOUSE_ENTER = 'onMouseEnter',
  ON_MOUSE_LEAVE = 'onMouseLeave',
  ON_MOUSE_UP = 'onMouseUp',
  ON_NEW_SUBMISSION = 'onNewSubmission',
  ON_REFRESH = 'onRefresh',
  ON_WATCH = 'onWatch',
  OPERATION_EXECUTED = 'system.operation.executed',
  OPERATION_SUBMITTED = `system.operation.submitted`,
  READY_COMPLETED = 'system.runtime.ready.completed',
  RESOLVE_VALUE_DONT_USE = 'system.resolution.value',
  RUNTIME_CONSTRUCTED = 'system.constructed',
  RUNTIME_DESTROY = 'system.destroy',
  SLOT_CLEARED = 'system.slot.cleared',
  SLOT_CREATED = 'system.slot.created',
  SPECIFICATION_ADDED = 'system.specification.added',
  SPEC_EVENT_DISPATCH = 'system.specification.event.dispatch',
  SPEC_EVENT_DISPATCH_COMPLETED = 'system.specification.event.dispatch.completed',
  STARTED = `system.started`,
  SUBMISSION_FAILED = 'system.submission.failed',
  SUBMISSION_LOADED = 'system.submission.loaded',
  SUBMISSION_SAVED = 'system.submission.saved',
  SUBMISSION_SAVING = 'system.submission.saving',
  SUBSCRIBER_REGISTERED = 'system.meta.listener.registered',
  SUBSCRIBER_UNREGISTERED = 'system.meta.listener.unregistered',
  WATCH_FULFILLED = 'system.event.watch.fulfilled',
  WATCH_REGISTERED = `system.event.watch.registered`,
  WATCH_TRIGGERED = `system.event.watch.triggered`,
  WATCH_UNFULFILLED = 'system.event.watch.unfulfilled',
}
