export enum SyntaxTokenType {
  API_CALL_ERROR = 'API_CALL_ERROR',
  DOM_EVENT = 'DOM_EVENT',
  R1_GRID_ROW = 'R1_GRID_ROW',
  R1_GRID_COL = 'R1_GRID_COL',
  DYNAMIC = 'DYNAMIC',
  GET_ALL = 'GET_ALL',
  GET_ALL_CHILDREN = 'GET_ALL_CHILDREN',
  GET_MODULE_CHILDREN = 'GET_MODULE_CHILDREN',
  CONTEXT_VALIDATION_RESULTS = 'CONTEXT_VALIDATION_RESULTS',
  GET_DEFINITIONS = 'GET_DEFINITIONS',
  INCLUDES = 'INCLUDES',
  INDEX = 'INDEX',
  MODULE_STATE = 'MODULE_STATE',
  OPERATION_CONTEXT = 'OPERATION_CONTEXT',
  PROPERTY = 'PROPERTY',
  RETURN = 'RETURN',
  ROOT_STATE = 'ROOT_STATE',
  ROUTE_STATE = 'ROUTE_STATE',
  RUNTIME_EVENT = 'RUNTIME_EVENT',
  TARGET = 'TARGET',
  TRANSLATE = 'TRANSLATE',
  SUBMISSION_DATA = 'SUBMISSION_DATA',
  UTILITY = 'UTILITY',
}

export type SyntaxToken = {
  type: SyntaxTokenType
  // TODO: rename to identifier (or just something better)
  name: string | number
  next?: SyntaxToken
}
