export enum InitializerEventTypes {
  NEW_SUBMISSION = 'NEW_SUBMISSION',
  EXECUTE = 'EXECUTE',
  EDIT_SUBMISSION = 'EDIT_SUBMISSION',
  MANUAL = 'MANUAL',
  // DOM EVENTS
  BEFORE_UNLOAD = 'BEFORE_UNLOAD',
}
